assets:
  js_prod:
  - bundles/bibsdbinfoportrait/assets/build/bibsdbinfoportrait.js
modules:
  toolsModule:
    files:
      - bundles/bibsdbinfoportrait/apps/toolsModule/info-portrait-text-editor.js
apps: